version: '3.8'

services:
  ai-voice:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
      - ./users.json:/app/users.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

